# Generated by Django 4.0.10 on 2023-11-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
