# Generated by Django 4.0.10 on 2023-11-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
