# Generated by Django 4.0.10 on 2023-11-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0004_alter_comentarios_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='commentID',
            field=models.IntegerField(),
        ),
    ]
