# Generated by Django 4.0.10 on 2023-11-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0005_alter_respuesta_commentid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comentarios',
            table=None,
        ),
        migrations.AlterModelTable(
            name='respuesta',
            table=None,
        ),
    ]
