# Generated by Django 4.0.10 on 2023-11-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0006_alter_comentarios_table_alter_respuesta_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comentarios',
            table='Comentarios',
        ),
        migrations.AlterModelTable(
            name='respuesta',
            table='Respuesta',
        ),
    ]
