# Generated by Django 4.2.6 on 2023-10-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_auto_20231024_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
