# Generated by Django 4.0.10 on 2023-10-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imageproj',
            field=models.FileField(null=True, upload_to='proyectos/'),
        ),
    ]
