# Generated by Django 4.2.5 on 2023-11-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=255)),
                ('Descripcion', models.TextField()),
                ('mes', models.IntegerField(null=True, verbose_name='mes')),
                ('imageproducto', models.ImageField(null=True, upload_to='temporada/')),
            ],
        ),
    ]
