# Generated by Django 4.2.5 on 2023-11-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiproductost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporada',
            options={'verbose_name_plural': 'Meses'},
        ),
        migrations.AlterField(
            model_name='temporada',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True, verbose_name='Mes'),
        ),
    ]
