# Generated by Django 4.2.5 on 2023-11-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiproductost', '0004_alter_temporada_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='mes',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20, null=True, verbose_name='Mes'),
        ),
    ]
