# Generated by Django 4.2.5 on 2023-11-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiproductost', '0005_alter_temporada_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=20, null=True, verbose_name='Mes'),
        ),
    ]
